language: node_js
node_js:
- '8'

env:
  global:
  - SAUCE_USERNAME=Exonum
  - secure: H6/KnkjbexZK1/jV/Z7zEUVI/CG7+0wi46uqgv4VP2RdJNkUN4oDVpUbzBHVW92Eb1JFw1FiQkRoKmvo2y4InuwmrRmc4hwSM5NNdPImmj6734nvkJf+p8c/kPTeYiz68MxqfRFef3tOZsQQM5tZjI2Qi4T+Z53MnFys8WFLkuvvUvKi9f/jj7Qkk2staoGIVIfiSRCkblrNrS27gIobz7lxuAcddS3lejLotE5CKB9V2W4YLqOGSXGBSMy4oStQqp2DllYun9/1Qq6ksrvfPFHHZoYL8dyI7IuiBC72VnF45D+gK83gAPGup9mDz7Q3QXWembXrBotHz+2tIgIijOjZ6cRVxmVM5x1QmSuZb+KdCjCUGZVNJlfLt5arNCBdiLYYdwgXtLHL65l00hmWUKBoV4WNxeI3/5yDruxEtnaKrwzgri44m6is+jvmfxEkM1Nb1gBw0+q+reKS84q+mobnUkLCHrD7+9Esxckr9a6FQBOce/Yvewvs30sS5iO9ynkEE9QpSsexF3D+exbUiHZCCFTCuoLwZGlCY/OGLT41C82C466b+tDkz9Q5hTMs8muOii74Xq7g/chTgSWuVDT/00BfUhaVQCZ/mx9u4xVC0cV3pkchq+LPbb+buWvuZsio9AFcE5h20Absv1LrNAjflec9x5WXreKtMHX9Q64=

cache:
  directories:
  - node_modules

script:
- npm run compile
- npm run test
- npm run test-saucelabs

after_success:
- npm run coveralls

deploy:
  skip_cleanup: true
  provider: npm
  email: exonum.bitfury@gmail.com
  api_key:
    secure: RWLL4X1LIMnjMZ+CXPZ06Xw/KjXLeplQXLnE32R6Mv7cju56H6fYVIILQoD8TXt9l4jt2prjrLhTtXL4bYWcDOA8r+amRJntnXMdk0Toy0t54h4unaJZ7A5qdsgJpdf7XPueSAUUfwTCKKslfwPkD/4uGNrKJYaRJipKznhzhUM3+Rnh2QLSvqsJrR08aC7NF4xLTH3TKzDMQ8QkQe77Yh5RX2MPaD3iNPcvkWiiwKdmVv5VhJKO/VM7+KL3xS0EQs1LxVerCAsgJ4jEnk2nmx1MyPIjXssZu6u05wdVbbk7PHQmSWeSU56uDcBwzNyscxvEspUctyBch1O+3byjPLaz1dCIVMzb1RY+tkwqhQJSge7NIzXaNpWyRwHByYOcnT2m7wo28vWUnFYLHVW/PRkHaHWqHQl9gdLF0GBQRz8O+BlMaZaP5FiS4iY3o78swNFxBoeM16Am5I80RreOiinKBJm6fQOr5AgTEhecMrEz70aemxhKpTx+EGmSVuoVy1A3X75YVlKRRhOFMU/2yKOifIsKIgGmTzPgHZsOXVlk85EBq8lx4pMJgQVTeiQZ+NfG9KQJJ5K4rfIe+PUgSMvEOK3dGG2FjiQChYazqA3VBnV9ytt+8GFs7f7GiEIOK2AD7c7aBggeyoKfR8m5HcVlLnylkVIH31JMtIU+1vc=
  on:
    branch: master
    tags: true
